### ISSUE TITLE
Cần thêm âm thanh cho game

### ISSUE THREAD

**Issue by davishoang96** [FPlane/2017-14BIT-GROUP_H-Project#10]
- flap sound
- die sound
- music
- score sound

**Comment by hienvinhpro** [comment]
đã thêm flapsound và diedsound

**Comment by davishoang96** [comment]
viết lại hàm OnCollision2DEnter mới đúng

**Comment by jaddenwoo** [comment]
Đã viết lại hàm OnCollision2DEnter
